# Generated by Django 5.1.2 on 2024-11-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_1',
            field=models.TextField(blank=True, help_text='Первый вариант для выбора', null=True),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_2',
            field=models.TextField(blank=True, help_text='Второй вариант для выбора', null=True),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_3',
            field=models.TextField(blank=True, help_text='Третий вариант для выбора', null=True),
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_4',
            field=models.TextField(blank=True, help_text='Четвёртый вариант для выбора', null=True),
        ),
    ]
