# Generated by Django 5.1.2 on 2024-11-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_matchingpair_right_option_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='noAnswer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='left_side_1',
            field=models.TextField(default='noAnswer', help_text='Первая неизменяемая левая часть'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='left_side_2',
            field=models.TextField(default='noAnswer', help_text='Вторая неизменяемая левая часть'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_1',
            field=models.TextField(default='noAnswer', help_text='Первый вариант для выбора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_2',
            field=models.TextField(default='noAnswer', help_text='Второй вариант для выбора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_3',
            field=models.TextField(default='noAnswer', help_text='Третий вариант для выбора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchingpair',
            name='right_option_4',
            field=models.TextField(default='noAnswer', help_text='Четвёртый вариант для выбора'),
            preserve_default=False,
        ),
    ]
