# Generated by Django 5.1.2 on 2024-12-09 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_subject_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usage_type',
            field=models.CharField(choices=[('single', 'Single'), ('subscription', 'Subscription')], default='single', max_length=20, verbose_name='Тип использования'),
        ),
    ]
